#ifndef TEST_REPLACE_H
#define TEST_REPLACE_H

#include <CUnit/Basic.h>

void test_replace_with_null_string_to_replace_returns_null();
void test_replace_with_invalid_string_to_replace_returns_null();
void test_replace_with_empty_string_to_replace_returns_empty_string();

void test_replace_with_valid_string_to_replace_and_null_replace_pattern_returns_null();
void test_replace_with_valid_string_to_replace_and_invalid_replace_pattern_returns_null();
void test_replace_with_valid_string_to_replace_and_empty_replace_pattern_returns_returns_input_string();

void test_replace_with_valid_string_to_replace_and_valid_replace_pattern_and_null_replace_returns_null();
void test_replace_with_valid_string_to_replace_and_valid_replace_pattern_and_invalid_replace_returns_null();
void test_replace_with_valid_string_to_replace_and_valid_replace_pattern_and_empty_replace_returns_new_string();

void test_replace_with_valid_string_to_replace_and_valid_replace_pattern_returns_new_string();
void test_replace_with_valid_string_to_replace_and_unknown_replace_pattern_returns_new_string();
void test_replace_with_valid_string_to_replace_and_valid_replace_pattern_returns_new_shorter_string();
void test_replace_with_valid_string_to_replace_and_valid_replace_pattern_returns_new_longer_string();

CU_pSuite run_replace_suite();

#endif
